name: fp_traefik-dev

services:
  redis:
    image: redis:7.4-alpine
    ports: [6379:6379/tcp]

  traefik:
    depends_on:
      - redis
    image: traefik:v3.1
    ports:
      - 80:80/tcp
      - 8080:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --accesslog=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.redis.endpoints=redis:6379
      - --entrypoints.http.address=:80

  fp_traefik:
    depends_on:
      - redis
    build:
      context: .
    environment:
      FP_TRAEFIK_REDIS_URL: redis://redis:6379/0
      FP_TRAEFIK_SUBDOMAIN_HOST: example.org
      FP_TRAEFIK_DEFAULT_SERVICE: frp@docker
      FP_TRAEFIK_DEFAULT_ENTRYPOINT: http
      FP_TRAEFIK_DEFAULT_ROUTER_NAME_PREFIX: frp-

  frps:
    depends_on:
      - fp_traefik
    image: ghcr.io/fatedier/frps:v0.61.0
    entrypoint: sh
    command:
      - -euc
      - |-
        cat << EOF > /frps.toml
        bindPort = 7000
        vhostHTTPPort = 8080
        subdomainHost = "example.org"
        
        [[httpPlugins]]
        name = "fp_traefik"
        addr = "fp_traefik:8080"
        path = "/handler"
        ops = [
            "NewProxy",
            "CloseProxy",
            "NewWorkConn",
        ]
        EOF
        frps -c /frps.toml
    ports:
      - 7000:7000/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.frp.service=frp
      - traefik.http.services.frp.loadbalancer.server.port=8080

  whoami:
    image: traefik/whoami:latest

  frpc:
    depends_on:
      - frps
      - whoami
    image: ghcr.io/fatedier/frpc:v0.61.0
    entrypoint: sh
    command:
      - -euc
      - |-
        cat << EOF > /frpc.toml
        serverAddr = "frps"
        serverPort = 7000
        
        [[proxies]]
        name = "whoami"
        localIP = "whoami"
        localPort = 80
        type = "http"
        subdomain = "www"
        locations = ["/foo", "/bar"]
        EOF
        frpc -c /frpc.toml
